added kubeconfig generator

diff --git a/bin/gke-create b/bin/gke-create
--- a/bin/gke-create
+++ b/bin/gke-create
@@ -56,3 +56,17 @@ echo "GKE_CLUSTER_NAME=${GKE_CLUSTER_NAME}"
 cf_export GKE_CLUSTER_NAME
 
 gcloud --quiet container clusters create ${GKE_CLUSTER_NAME} $@
+if [[ $? != 0 ]]; then
+      err "Failed to create cluster $GKE_CLUSTER_NAME"
+fi
+
+KUBECONFIG_DIR=/codefresh/volume/.kube
+mkdir -p $KUBECONFIG_DIR
+export KUBECONFIG=${KUBECONFIG_DIR}/${GKE_CLUSTER_NAME}-config
+
+generateKubeconfig > ${KUBECONFIG_DIR}/${GKE_CLUSTER_NAME}-config
+if [[ $? != 0 ]]; then
+      err "Failed to get kubeconfig for cluster $GKE_CLUSTER_NAME"
+fi
+
+cf_export KUBECONFIG
diff --git a/bin/gke-delete b/bin/gke-delete
--- a/bin/gke-delete
+++ b/bin/gke-delete
@@ -23,3 +23,8 @@ if [[ -z ${GKE_CLUSTER_NAME} ]]; then
 fi
 
 gcloud --quiet container cluster delete ${GKE_CLUSTER_NAME}
+if [[ $? != 0 ]]; then
+  err "Failed create cluster"
+fi
+
+echo "Getting kubeconfig"
diff --git a/bin/helpers b/bin/helpers
--- a/bin/helpers
+++ b/bin/helpers
@@ -5,5 +5,49 @@ err() { echo -e "\e[31mERR ---> $1\e[0m" ; exit 1; }
 
 activateServiceAccount() {
 	[[ -z "$GOOGLE_SERVICE_ACCOUNT_KEY" ]] && err "Please set the service-account env var!"
-	gcloud auth activate-service-account --key-file <<<$(echo $GOOGLE_SERVICE_ACCOUNT_KEY)
+    
+	export CLOUDSDK_CORE_PROJECT=$(jq -r '.project_id' <(echo $GOOGLE_SERVICE_ACCOUNT_KEY) )
+    [[ -z "$CLOUDSDK_CORE_PROJECT" ]] && err "Cannot get project_id - invalid GOOGLE_SERVICE_ACCOUNT_KEY"
+	gcloud config set project $CLOUDSDK_CORE_PROJECT
+	
+	gcloud auth activate-service-account --key-file <(echo $GOOGLE_SERVICE_ACCOUNT_KEY)	
+	if [[ $? != 0 ]]; then
+       err "Cannot authenticate to Google cloud with given GOOGLE_SERVICE_ACCOUNT_KEY"
+	fi
+}
+
+generateKubeconfig() {
+  GKE_CLUSTER_NAME=${1:-$GKE_CLUSTER_NAME}
+  JQ_QUERY='{
+        "apiVersion": "v1",
+		"kind": "Config",
+        "clusters": [{
+		    "name": .name ,
+            "cluster": {
+			  "certificate-authority-data": .masterAuth.clusterCaCertificate ,
+			  "server": ("https://" + .endpoint)
+		    }
+	    }],
+        "contexts": [
+            {
+                "context": {
+                    "cluster": .name,
+                    "user": ( .name + "-admin" )
+                },
+                "name": .name
+            }
+        ],
+		"current-context": .name,
+		"users": [
+            {
+                "name": ( .name + "-admin" ),
+				"user": {
+					"client-certificate-data": .masterAuth.clientCertificate , 
+					"client-key-data": .masterAuth.clientKey 
+				}
+			}
+		]
+    }'
+
+	gcloud container clusters describe --project=codefresh-load --project=$CLOUDSDK_CORE_PROJECT $GKE_CLUSTER_NAME --format=json | jq -r "$JQ_QUERY"
 }
